export class Product {
     id!: number
     title!: string
     cateID!: number
     tranzaction!: string
     city!: string
     district!: string
     ward!: string
     userID!: number
     size!: number
     width!: number
     ppmm!: number
     deposit!: number
     balcony!: string
     interior!: string
     description!: string
     status!: string
     block!: string
     floor!: string
     iscorner!: boolean
     badroom!: number
     toilet!: number
     maindirect!: string
     longi!: number
     lati!: number
     postOn!: Date
     type!: string
     legality!: string
     active!: boolean
}
